# -*- coding: utf-8 -*-
"""OCRWdataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzbk7TbmsvvZNz7TWgr701slv9Cm9AwQ
"""

from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset("Teklia/IAM-line")

print(dataset)

sample = dataset["train"][2]

image = sample["image"]
text = sample["text"]

plt.imshow(image)
plt.axis("off")
plt.title("First Handwritten Image")
plt.show()

print("Extracted Text:")
print(text)

pip install jiwer

from jiwer import cer, wer

ground_truth = "The quick brown fox jumps over the lazy dog"

predicted_text = "The quik brown fox jump over the lazy dog"

cer_score = cer(ground_truth, predicted_text)

cer_score = cer(ground_truth, predicted_text)

wer_score = wer(ground_truth, predicted_text)

print(f"CER: {cer_score:.4f}")
print(f"WER: {wer_score:.4f}")

character_accuracy = (1 - cer_score) * 100
word_accuracy = (1 - wer_score) * 100

print(f"Character Accuracy: {character_accuracy:.2f}%")
print(f"Word Accuracy: {word_accuracy:.2f}%")

pip install datasets jiwer pytesseract pillow matplotlib

!sudo apt-get update
!sudo apt-get install -y tesseract-ocr

from datasets import load_dataset
import matplotlib.pyplot as plt
import pytesseract
from jiwer import cer, wer

dataset = load_dataset("Teklia/IAM-line")

sample = dataset["test"][0]

image = sample["image"]
ground_truth = sample["text"]

plt.imshow(image)
plt.axis("off")
plt.title("Handwritten Image")
plt.show()

predicted_text = pytesseract.image_to_string(image)


print("Ground Truth")
print(ground_truth)

print("OCR Prediction")
print(predicted_text)

cer_score = cer(ground_truth, predicted_text)
wer_score = wer(ground_truth, predicted_text)

character_accuracy = (1 - cer_score) * 100
word_accuracy = (1 - wer_score) * 100


print("Evaluation")
print(f"Character Error Rate (CER): {cer_score:.4f}")
print(f"Word Error Rate (WER): {wer_score:.4f}")
print(f"Character Accuracy: {character_accuracy:.2f}%")
print(f"Word Accuracy: {word_accuracy:.2f}%")

print(len(dataset["train"]))
print(len(dataset["test"]))

